prod:
  image: vizzuality/gfw-ogr-api:1.0.1${STAGING}
  ports:
    - "3200"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-ogr-api${STAGING}
